# Generated by Django 5.1.3 on 2025-11-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Status',
        ),
        migrations.AddField(
            model_name='level',
            name='subLevel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='stared',
            field=models.BooleanField(default=False),
        ),
    ]
