# Generated by Django 5.1.3 on 2025-11-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_status_remove_student_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='JoinDate',
        ),
    ]
