# Generated by Django 5.1.3 on 2025-12-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_joindate'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
    ]
