# Generated by Django 5.1.3 on 2025-12-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_person_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Permissions',
            field=models.BooleanField(default=True),
        ),
    ]
