# Generated by Django 5.1.3 on 2025-12-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_teacher_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Person',
            new_name='PersonID',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Person',
            new_name='PersonID',
        ),
    ]
