# Generated by Django 5.1.3 on 2025-12-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_person_student_personid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='PersonID',
            new_name='id',
        ),
    ]
