# Generated by Django 5.1.3 on 2025-12-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_personid_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='PersonID',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='PersonID',
            new_name='Person',
        ),
    ]
