# Generated by Django 5.1.3 on 2025-12-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_personid_student_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='token_version',
            field=models.IntegerField(default=1),
        ),
    ]
