# Generated by Django 5.1.3 on 2025-12-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_person_token_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarLevel',
            fields=[
                ('StarID', models.AutoField(primary_key=True, serialize=False)),
                ('MinRating', models.FloatField()),
                ('MaxRating', models.FloatField()),
                ('NumStars', models.IntegerField()),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
