# Generated by Django 5.1.3 on 2025-12-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_starlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='StarredCount',
            new_name='RatingCount',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='stared',
            new_name='Stared',
        ),
        migrations.AddField(
            model_name='teacher',
            name='StarLevel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.starlevel'),
        ),
    ]
