# Generated by Django 5.1.3 on 2025-12-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_starredcount_teacher_ratingcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='QuestionsAdded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='QuestionsDeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='QuestionsEdited',
            field=models.IntegerField(default=0),
        ),
    ]
