# Generated by Django 5.1.3 on 2025-10-27 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('AchievementID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='achievements/')),
                ('PointsRequired', models.IntegerField()),
                ('TargetRole', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('UserAchievementID', models.AutoField(primary_key=True, serialize=False)),
                ('DateEarned', models.DateField()),
                ('Achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
