# Generated by Django 5.1.3 on 2025-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='numberofstars',
            field=models.IntegerField(default=0),
        ),
    ]
