# Generated by Django 5.1.3 on 2025-12-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievement_numberofstars'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='ActivityType',
            field=models.CharField(choices=[('stars', 'Stars'), ('questions_added', 'Questions Added'), ('questions_edited', 'Questions Edited'), ('questions_deleted', 'Questions Deleted')], default='stars', max_length=50),
        ),
    ]
