# Generated by Django 5.1.3 on 2025-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_achievement_activitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='ActivityType',
            field=models.CharField(choices=[('stars', 'Stars'), ('studnet', 'Studnet'), ('questions_added', 'Questions Added'), ('questions_edited', 'Questions Edited'), ('questions_deleted', 'Questions Deleted')], default='stars', max_length=50),
        ),
    ]
