# Generated by Django 5.1.3 on 2026-03-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_achievement_activitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
