# Generated by Django 5.1.3 on 2026-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_userachievement_is_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='ActivityType',
            field=models.CharField(choices=[('stars', 'Stars'), ('student', 'Student'), ('questions_added', 'Questions Added'), ('questions_edited', 'Questions Edited'), ('questions_deleted', 'Questions Deleted')], default='stars', max_length=50),
        ),
    ]
