# Generated by Django 5.1.3 on 2026-03-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_alter_achievement_activitytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='is_notified',
        ),
    ]
