# Generated by Django 5.1.3 on 2025-10-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeExam',
            fields=[
                ('ChallengeExamID', models.AutoField(primary_key=True, serialize=False)),
                ('ChallengeName', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('PenaltyPoints', models.IntegerField(default=0)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('IsUnlocked', models.BooleanField(default=False)),
                ('MinLevelRequired', models.IntegerField()),
                ('PreviousChallengeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.challengeexam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionName', models.CharField(max_length=200)),
                ('QuestionText', models.TextField()),
                ('Category', models.CharField(max_length=100)),
                ('Rate', models.IntegerField(choices=[(100, 'Easy'), (200, 'Medium'), (300, 'Hard')])),
                ('Points', models.IntegerField()),
                ('QuestionType', models.CharField(choices=[('Regular', 'Regular'), ('Challenge', 'Challenge')], max_length=50)),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('AnswerText', models.TextField()),
                ('IsCorrect', models.BooleanField()),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('StudentAnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('IsCorrect', models.BooleanField()),
                ('PointsEarned', models.IntegerField()),
                ('RateByStudent', models.IntegerField()),
                ('AnsweredAt', models.DateTimeField()),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('SelectedAnswer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.answer')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentChallenge',
            fields=[
                ('StudentChallengeID', models.AutoField(primary_key=True, serialize=False)),
                ('ChallengeStatus', models.CharField(max_length=50)),
                ('ChallengeScore', models.IntegerField()),
                ('AttemptsCount', models.IntegerField(default=1)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('IsCompleted', models.BooleanField(default=False)),
                ('ChallengeExam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.challengeexam')),
                ('LevelAtAttempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.level')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]
