# Generated by Django 5.1.3 on 2025-12-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchallenge',
            name='LevelAtAttempt',
            field=models.IntegerField(default=0),
        ),
    ]
