# Generated by Django 5.1.3 on 2025-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_studentchallenge_levelatattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='AnsweredAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
