# Generated by Django 5.1.3 on 2026-03-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_studentanswer_answeredat'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeexam',
            name='Scoreofchallenge',
            field=models.IntegerField(null=True),
        ),
    ]
