# Generated by Django 5.1.3 on 2026-03-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_challengeexam_scoreofchallenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeexam',
            old_name='MinLevelRequired',
            new_name='MinPointsRequired',
        ),
    ]
