# Generated by Django 5.1.3 on 2026-03-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_rename_minlevelrequired_challengeexam_minpointsrequired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeexam',
            name='Scoreofchallenge',
        ),
        migrations.AddField(
            model_name='studentchallenge',
            name='Scoreofchallenge',
            field=models.IntegerField(null=True),
        ),
    ]
