# Generated by Django 5.1.3 on 2026-03-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_challengeexam_scoreofchallenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchallenge',
            name='Questions',
            field=models.ManyToManyField(related_name='challenge_attempts', to='exams.question'),
        ),
    ]
