# Generated by Django 5.1.3 on 2026-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_studentchallenge_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchallenge',
            name='ChallengeScore',
            field=models.IntegerField(null=True),
        ),
    ]
