# Generated by Django 5.1.3 on 2026-05-21 07:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_teacher_questionsadded_teacher_questionsdeleted_and_more'),
        ('exams', '0008_alter_studentchallenge_challengescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('CardID', models.AutoField(primary_key=True, serialize=False)),
                ('Guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=120)),
                ('Type', models.CharField(choices=[('PERCENT_POINTS', 'Percent Points'), ('FLAT_POINTS', 'Flat Points'), ('FORCE_DIFFICULTY', 'Force Difficulty'), ('FORCE_CATEGORY', 'Force Category')], max_length=30)),
                ('Value', models.CharField(max_length=120)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentChaosSession',
            fields=[
                ('SessionID', models.AutoField(primary_key=True, serialize=False)),
                ('DayKey', models.DateField(default=django.utils.timezone.now)),
                ('ChaosScore', models.IntegerField(default=0)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('ChosenCard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_sessions', to='exams.card')),
                ('DailyCard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sessions', to='exams.card')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('Student', 'DayKey')},
            },
        ),
    ]
