# Generated by Django 5.1.3 on 2026-05-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_card_studentchaossession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Guid',
        ),
    ]
