# Generated by Django 5.1.3 on 2026-05-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_remove_card_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchaossession',
            name='Questions',
            field=models.ManyToManyField(blank=True, related_name='chaos_sessions', to='exams.question'),
        ),
    ]
